export type MealOption = { name: string; slot: string };

/**
 * Sample meal options by slot, used for dev-mode simulated plan generation.
 * Includes allergen-safe alternatives per slot.
 */
export const SAMPLE_MEALS: Record<string, MealOption[]> = {
  Breakfast: [
    { name: 'Greek Yogurt Parfait with Berries', slot: 'Breakfast' },
    { name: 'Scrambled Eggs with Spinach Toast', slot: 'Breakfast' },
    { name: 'Overnight Oats with Banana', slot: 'Breakfast' },
    { name: 'Protein Smoothie Bowl', slot: 'Breakfast' },
    { name: 'Avocado Toast with Poached Eggs', slot: 'Breakfast' },
    { name: 'Whole Grain Pancakes with Berries', slot: 'Breakfast' },
    { name: 'Breakfast Burrito with Turkey', slot: 'Breakfast' },
    { name: 'Fresh Fruit Salad with Chia Seeds', slot: 'Breakfast' },
    { name: 'Bacon and Sweet Potato Hash', slot: 'Breakfast' },
    { name: 'Coconut Yogurt Parfait', slot: 'Breakfast' },
    { name: 'Smoothie with Coconut Milk', slot: 'Breakfast' },
    { name: 'Nut Butter Toast with Banana', slot: 'Breakfast' },
    { name: 'Chia Pudding with Fruit', slot: 'Breakfast' },
    { name: 'Scrambled Eggs with Avocado', slot: 'Breakfast' },
    { name: 'Gluten-Free Protein Pancakes', slot: 'Breakfast' },
  ],
  Lunch: [
    { name: 'Grilled Chicken Caesar Salad', slot: 'Lunch' },
    { name: 'Turkey and Avocado Wrap', slot: 'Lunch' },
    { name: 'Quinoa Power Bowl', slot: 'Lunch' },
    { name: 'Mediterranean Chicken Bowl', slot: 'Lunch' },
    { name: 'Salmon Poke Bowl', slot: 'Lunch' },
    { name: 'Southwest Black Bean Bowl', slot: 'Lunch' },
    { name: 'Asian Chicken Lettuce Wraps', slot: 'Lunch' },
    { name: 'Grilled Chicken Buddha Bowl', slot: 'Lunch' },
    { name: 'Beef and Vegetable Stir-Fry', slot: 'Lunch' },
    { name: 'Lentil Soup with Side Salad', slot: 'Lunch' },
    { name: 'Chicken Rice Bowl', slot: 'Lunch' },
    { name: 'Mediterranean Salad with Grilled Chicken', slot: 'Lunch' },
    { name: 'Stuffed Bell Peppers with Beef', slot: 'Lunch' },
  ],
  Dinner: [
    { name: 'Grilled Salmon with Roasted Vegetables', slot: 'Dinner' },
    { name: 'Chicken Stir-Fry with Brown Rice', slot: 'Dinner' },
    { name: 'Lean Beef Tacos with Corn Tortillas', slot: 'Dinner' },
    { name: 'Baked Cod with Sweet Potato', slot: 'Dinner' },
    { name: 'Turkey Meatballs with Zucchini Noodles', slot: 'Dinner' },
    { name: 'Herb-Crusted Chicken Thighs', slot: 'Dinner' },
    { name: 'Shrimp and Vegetable Skewers', slot: 'Dinner' },
    { name: 'Grilled Chicken Breast with Asparagus', slot: 'Dinner' },
    { name: 'Beef Stir-Fry with Vegetables', slot: 'Dinner' },
    { name: 'Pork Tenderloin with Roasted Potatoes', slot: 'Dinner' },
    { name: 'Lentil Curry with Rice', slot: 'Dinner' },
    { name: 'Vegetable Paella', slot: 'Dinner' },
  ],
  'Snack 1': [
    { name: 'Apple Slices with Almond Butter', slot: 'Snack 1' },
    { name: 'Protein Bar', slot: 'Snack 1' },
    { name: 'Trail Mix (30g)', slot: 'Snack 1' },
    { name: 'Cottage Cheese with Pineapple', slot: 'Snack 1' },
    { name: 'Rice Cakes with Peanut Butter', slot: 'Snack 1' },
    { name: 'Hummus with Veggie Sticks', slot: 'Snack 1' },
    { name: 'Hard-Boiled Eggs (2)', slot: 'Snack 1' },
    { name: 'Fresh Berries', slot: 'Snack 1' },
    { name: 'Carrot Sticks with Guacamole', slot: 'Snack 1' },
    { name: 'Rice Cakes with Avocado', slot: 'Snack 1' },
    { name: 'Beef Jerky', slot: 'Snack 1' },
    { name: 'Olives', slot: 'Snack 1' },
    { name: 'Coconut Yogurt Cup', slot: 'Snack 1' },
    { name: 'Fresh Fruit Cup', slot: 'Snack 1' },
    { name: 'Nut Butter on Celery', slot: 'Snack 1' },
  ],
  'Snack 2': [
    { name: 'Mixed Nuts (25g)', slot: 'Snack 2' },
    { name: 'Greek Yogurt Cup', slot: 'Snack 2' },
    { name: 'Banana with Peanut Butter', slot: 'Snack 2' },
    { name: 'Edamame (100g)', slot: 'Snack 2' },
    { name: 'Dark Chocolate (20g) with Almonds', slot: 'Snack 2' },
    { name: 'Cheese Stick with Crackers', slot: 'Snack 2' },
    { name: 'Whey Protein Shake', slot: 'Snack 2' },
    { name: 'Fresh Pear', slot: 'Snack 2' },
    { name: 'Roasted Chickpeas', slot: 'Snack 2' },
    { name: 'Beef Jerky', slot: 'Snack 2' },
    { name: 'Sunflower Seeds', slot: 'Snack 2' },
    { name: 'Coconut Chia Pudding', slot: 'Snack 2' },
    { name: 'Dried Fruit', slot: 'Snack 2' },
    { name: 'Protein Shake (Whey)', slot: 'Snack 2' },
  ],
  'Snack 3': [
    { name: 'Apple Slices with Peanut Butter', slot: 'Snack 3' },
    { name: 'Protein Smoothie', slot: 'Snack 3' },
    { name: 'Trail Mix (30g)', slot: 'Snack 3' },
    { name: 'Cottage Cheese with Berries', slot: 'Snack 3' },
    { name: 'Rice Cakes with Almond Butter', slot: 'Snack 3' },
    { name: 'Beef Jerky', slot: 'Snack 3' },
    { name: 'Hard-Boiled Eggs (2)', slot: 'Snack 3' },
  ],
  'Snack 4': [
    { name: 'Mixed Nuts (25g)', slot: 'Snack 4' },
    { name: 'Greek Yogurt Cup', slot: 'Snack 4' },
    { name: 'Banana with Peanut Butter', slot: 'Snack 4' },
    { name: 'Edamame (100g)', slot: 'Snack 4' },
    { name: 'Dark Chocolate (20g)', slot: 'Snack 4' },
    { name: 'Cheese Stick', slot: 'Snack 4' },
    { name: 'Protein Shake', slot: 'Snack 4' },
  ],
  'Meal 4': [
    { name: 'Grilled Chicken Breast', slot: 'Meal 4' },
    { name: 'Turkey Meatballs', slot: 'Meal 4' },
    { name: 'Beef Stir-Fry', slot: 'Meal 4' },
    { name: 'Salmon Fillet', slot: 'Meal 4' },
    { name: 'Tofu Vegetable Bowl', slot: 'Meal 4' },
  ],
  'Meal 5': [
    { name: 'Chicken Thighs', slot: 'Meal 5' },
    { name: 'Lean Beef Steak', slot: 'Meal 5' },
    { name: 'Pork Tenderloin', slot: 'Meal 5' },
    { name: 'Cod Fillet', slot: 'Meal 5' },
    { name: 'Tempeh Bowl', slot: 'Meal 5' },
  ],
  'Meal 6': [
    { name: 'Grilled Chicken', slot: 'Meal 6' },
    { name: 'Ground Turkey', slot: 'Meal 6' },
    { name: 'Beef Roast', slot: 'Meal 6' },
    { name: 'Shrimp', slot: 'Meal 6' },
    { name: 'Edamame Bowl', slot: 'Meal 6' },
  ],
};

/**
 * Allergen keyword mapping for restriction checking.
 * Key: allergen name, Value: keywords that indicate the allergen in a meal name.
 */
export const ALLERGEN_KEYWORDS: Record<string, string[]> = {
  peanuts: ['peanut', 'almond', 'cashew', 'walnut', 'pecan', 'trail mix', 'mixed nuts'],
  'tree nuts': ['peanut', 'almond', 'cashew', 'walnut', 'pecan', 'trail mix', 'mixed nuts'],
  dairy: ['yogurt', 'cheese', 'milk', 'cottage cheese'],
  eggs: ['egg'],
  fish: ['salmon', 'cod', 'shrimp', 'poke', 'fish'],
  shellfish: ['salmon', 'cod', 'shrimp', 'poke', 'fish'],
  wheat: ['wheat', 'bread', 'pasta', 'tortilla', 'wrap', 'pancake', 'oat'],
  gluten: ['wheat', 'bread', 'pasta', 'tortilla', 'wrap', 'pancake', 'oat'],
  soy: ['soy', 'edamame', 'tofu'],
  sesame: ['sesame', 'hummus'],
};
