-- AlterTable
ALTER TABLE "FoodAlias" ADD COLUMN "per100gKcal" DOUBLE PRECISION;
ALTER TABLE "FoodAlias" ADD COLUMN "per100gProtein" DOUBLE PRECISION;
ALTER TABLE "FoodAlias" ADD COLUMN "per100gCarbs" DOUBLE PRECISION;
ALTER TABLE "FoodAlias" ADD COLUMN "per100gFat" DOUBLE PRECISION;
