/**
 * Seed script: Populates the FoodAlias table from the original INGREDIENT_NAME_MAP.
 *
 * For each alias→canonicalName pair, attempts to resolve a direct fdcId by
 * running a tsvector search against UsdaFood. This enables O(1) lookups for
 * known ingredients (skip search entirely).
 *
 * Usage:
 *   npx tsx packages/nutrition-engine/src/scripts/seed-food-aliases.ts
 *
 * Requires DATABASE_URL environment variable.
 */

import { PrismaClient } from '@prisma/client';

// Expanded alias map (~340 entries). Targets Claude's common output patterns,
// known test failures (exotic ingredients), compound names, and cooking variants.
const INGREDIENT_NAME_MAP: Record<string, string> = {
  // ======== PROTEINS ========
  eggs: 'egg whole raw',
  egg: 'egg whole raw',
  'egg whites': 'egg white raw',
  'egg white': 'egg white raw',
  'whole egg': 'egg whole raw',
  'whole eggs': 'egg whole raw',
  'hard boiled egg': 'egg hard boiled',
  'hard-boiled egg': 'egg hard boiled',
  'hard boiled eggs': 'egg hard boiled',
  'scrambled eggs': 'egg scrambled',
  'poached egg': 'egg poached',
  chicken: 'chicken breast raw',
  'chicken breast': 'chicken breast skinless raw',
  'chicken breasts': 'chicken breast skinless raw',
  'chicken thigh': 'chicken thigh skinless raw',
  'chicken thighs': 'chicken thigh skinless raw',
  'chicken drumstick': 'chicken drumstick raw',
  'chicken drumsticks': 'chicken drumstick raw',
  'chicken wings': 'chicken wing raw',
  'rotisserie chicken': 'chicken roasted',
  'grilled chicken': 'chicken breast grilled',
  'grilled chicken breast': 'chicken breast grilled',
  'baked chicken breast': 'chicken breast baked',
  salmon: 'atlantic salmon raw',
  'salmon fillet': 'atlantic salmon raw',
  'smoked salmon': 'salmon smoked',
  'canned salmon': 'salmon canned drained',
  tuna: 'tuna canned in water drained',
  'tuna steak': 'tuna yellowfin raw',
  'canned tuna': 'tuna canned in water drained',
  'tuna fish': 'tuna canned in water drained',
  shrimp: 'shrimp raw',
  prawns: 'shrimp raw',
  'ground beef': 'ground beef 90 lean raw',
  'lean ground beef': 'ground beef 93 lean raw',
  'ground turkey': 'ground turkey raw',
  'lean ground turkey': 'ground turkey 93 lean raw',
  'ground chicken': 'ground chicken raw',
  'ground pork': 'ground pork raw',
  tofu: 'tofu firm raw',
  'firm tofu': 'tofu firm raw',
  'silken tofu': 'tofu silken',
  'extra firm tofu': 'tofu extra firm raw',
  tempeh: 'tempeh',
  seitan: 'seitan',
  'beef steak': 'beef top sirloin raw',
  steak: 'beef top sirloin raw',
  'sirloin steak': 'beef top sirloin raw',
  'flank steak': 'beef flank steak raw',
  ribeye: 'beef ribeye raw',
  'beef tenderloin': 'beef tenderloin raw',
  'lamb chop': 'lamb loin chop raw',
  'lamb chops': 'lamb loin chop raw',
  lamb: 'lamb leg raw',
  'ground lamb': 'ground lamb raw',
  venison: 'venison raw',
  bison: 'bison ground raw',
  'duck breast': 'duck breast raw',
  duck: 'duck breast raw',
  'turkey bacon': 'turkey bacon',
  bacon: 'bacon pork raw',
  'canadian bacon': 'canadian bacon',
  sausage: 'pork sausage raw',
  'chicken sausage': 'chicken sausage',
  'turkey sausage': 'turkey sausage',
  'italian sausage': 'italian sausage pork raw',
  sardines: 'sardines canned in oil drained',
  anchovies: 'anchovies canned in oil drained',
  'crab meat': 'crab meat cooked',
  crab: 'crab meat cooked',
  lobster: 'lobster cooked',
  clams: 'clams cooked',
  mussels: 'mussels cooked',
  oysters: 'oysters raw',
  calamari: 'squid raw',
  squid: 'squid raw',
  octopus: 'octopus raw',
  cod: 'cod atlantic raw',
  'cod fillet': 'cod atlantic raw',
  'pork tenderloin': 'pork tenderloin raw',
  'pork chop': 'pork chop boneless raw',
  'pork chops': 'pork chop boneless raw',
  'pork loin': 'pork loin raw',
  'pulled pork': 'pork shoulder roasted',
  'turkey breast': 'turkey breast skinless raw',
  tilapia: 'tilapia raw',
  'mahi mahi': 'mahi mahi raw',
  'mahi-mahi': 'mahi mahi raw',
  scallops: 'scallops raw',
  halibut: 'halibut raw',
  swordfish: 'swordfish raw',
  trout: 'rainbow trout raw',
  'rainbow trout': 'rainbow trout raw',
  catfish: 'catfish raw',
  'sea bass': 'sea bass raw',
  snapper: 'red snapper raw',
  'red snapper': 'red snapper raw',
  grouper: 'grouper raw',
  'whey protein': 'whey protein powder',
  'protein powder': 'whey protein powder',
  'protein shake': 'whey protein powder',
  'collagen peptides': 'collagen peptides powder',
  'collagen powder': 'collagen peptides powder',

  // ======== GRAINS & STARCHES ========
  rice: 'white rice cooked',
  'white rice': 'white rice cooked',
  'brown rice': 'brown rice cooked',
  'sweet potato': 'sweet potato baked',
  'sweet potatoes': 'sweet potato baked',
  potato: 'potato baked flesh and skin',
  potatoes: 'potato baked flesh and skin',
  'russet potato': 'potato baked flesh and skin',
  'mashed potatoes': 'potato mashed',
  oats: 'oats rolled dry',
  oatmeal: 'oats rolled dry',
  'rolled oats': 'oats rolled dry',
  'steel cut oats': 'oats steel cut dry',
  'overnight oats': 'oats rolled dry',
  quinoa: 'quinoa cooked',
  pasta: 'pasta cooked',
  spaghetti: 'spaghetti cooked',
  penne: 'pasta penne cooked',
  'whole wheat pasta': 'whole wheat pasta cooked',
  bread: 'whole wheat bread',
  'white bread': 'white bread',
  'sourdough bread': 'sourdough bread',
  'rye bread': 'rye bread',
  'ezekiel bread': 'sprouted grain bread',
  'pita bread': 'pita bread whole wheat',
  pita: 'pita bread whole wheat',
  'english muffin': 'english muffin whole wheat',
  bagel: 'bagel plain',
  'rice noodles': 'rice noodles cooked',
  'soba noodles': 'soba noodles cooked',
  'udon noodles': 'udon noodles cooked',
  'egg noodles': 'egg noodles cooked',
  'glass noodles': 'cellophane noodles cooked',
  tortilla: 'flour tortilla',
  'flour tortilla': 'flour tortilla',
  'corn tortilla': 'corn tortilla',
  'whole wheat tortilla': 'whole wheat tortilla',
  naan: 'naan bread',
  'naan bread': 'naan bread',
  'jasmine rice': 'jasmine rice cooked',
  'basmati rice': 'basmati rice cooked',
  'wild rice': 'wild rice cooked',
  'arborio rice': 'arborio rice cooked',
  'sushi rice': 'sushi rice cooked',
  couscous: 'couscous cooked',
  farro: 'farro cooked',
  bulgur: 'bulgur cooked',
  'bulgur wheat': 'bulgur cooked',
  barley: 'barley pearl cooked',
  'pearl barley': 'barley pearl cooked',
  millet: 'millet cooked',
  amaranth: 'amaranth grain cooked',
  polenta: 'polenta cooked',
  grits: 'grits cooked',
  cornmeal: 'cornmeal yellow',
  cornstarch: 'cornstarch',
  'corn starch': 'cornstarch',
  flour: 'all purpose flour',
  'all purpose flour': 'all purpose flour',
  'all-purpose flour': 'all purpose flour',
  'whole wheat flour': 'whole wheat flour',
  'almond flour': 'almond flour',
  'coconut flour': 'coconut flour',
  granola: 'granola',
  'panko breadcrumbs': 'panko breadcrumbs',
  breadcrumbs: 'bread crumbs plain dry',
  'bread crumbs': 'bread crumbs plain dry',

  // ======== COOKED VARIANTS ========
  'quinoa cooked': 'quinoa cooked',
  'cooked quinoa': 'quinoa cooked',
  'rice cooked': 'white rice cooked',
  'cooked rice': 'white rice cooked',
  'pasta cooked': 'pasta cooked',
  'cooked pasta': 'pasta cooked',
  'lentils cooked': 'lentils cooked',
  'cooked lentils': 'lentils cooked',
  'cooked chicken': 'chicken breast cooked',
  'cooked chicken breast': 'chicken breast cooked',
  'cooked salmon': 'atlantic salmon cooked',
  'cooked shrimp': 'shrimp cooked',
  'cooked brown rice': 'brown rice cooked',
  'cooked sweet potato': 'sweet potato baked',
  'cooked black beans': 'black beans cooked',
  'cooked chickpeas': 'chickpeas cooked',
  'cooked barley': 'barley pearl cooked',

  // ======== VEGETABLES ========
  broccoli: 'broccoli raw',
  'broccoli florets': 'broccoli raw',
  spinach: 'spinach raw',
  'baby spinach': 'spinach raw',
  kale: 'kale raw',
  'mixed greens': 'mixed salad greens raw',
  'salad greens': 'mixed salad greens raw',
  'spring mix': 'mixed salad greens raw',
  arugula: 'arugula raw',
  'romaine lettuce': 'romaine lettuce raw',
  romaine: 'romaine lettuce raw',
  lettuce: 'lettuce green leaf raw',
  tomato: 'tomato raw',
  tomatoes: 'tomato raw',
  'cherry tomatoes': 'tomato cherry raw',
  'grape tomatoes': 'tomato grape raw',
  'sun dried tomatoes': 'sun dried tomatoes',
  'sun-dried tomatoes': 'sun dried tomatoes',
  'tomato paste': 'tomato paste',
  'tomato sauce': 'tomato sauce',
  'crushed tomatoes': 'tomatoes canned crushed',
  'diced tomatoes': 'tomatoes canned diced',
  'canned tomatoes': 'tomatoes canned whole',
  onion: 'onion raw',
  onions: 'onion raw',
  'red onion': 'onion red raw',
  'yellow onion': 'onion raw',
  'green onion': 'scallion raw',
  'green onions': 'scallion raw',
  scallions: 'scallion raw',
  shallot: 'shallot raw',
  shallots: 'shallot raw',
  leek: 'leek raw',
  leeks: 'leek raw',
  garlic: 'garlic raw',
  'garlic cloves': 'garlic raw',
  'minced garlic': 'garlic raw',
  ginger: 'ginger root raw',
  'fresh ginger': 'ginger root raw',
  'ginger root': 'ginger root raw',
  asparagus: 'asparagus raw',
  cauliflower: 'cauliflower raw',
  'bell pepper': 'bell pepper raw',
  'bell peppers': 'bell pepper raw',
  'red bell pepper': 'bell pepper red raw',
  'green bell pepper': 'bell pepper green raw',
  'yellow bell pepper': 'bell pepper yellow raw',
  jalapeno: 'jalapeno pepper raw',
  'jalapeno pepper': 'jalapeno pepper raw',
  zucchini: 'zucchini raw',
  'yellow squash': 'yellow squash raw',
  'butternut squash': 'butternut squash raw',
  'acorn squash': 'acorn squash raw',
  'spaghetti squash': 'spaghetti squash cooked',
  mushrooms: 'mushrooms raw white',
  mushroom: 'mushrooms raw white',
  'shiitake mushrooms': 'shiitake mushrooms raw',
  'portobello mushroom': 'portobello mushroom raw',
  'portobello mushrooms': 'portobello mushroom raw',
  'cremini mushrooms': 'cremini mushrooms raw',
  cucumber: 'cucumber raw',
  celery: 'celery raw',
  'green beans': 'green beans raw',
  cabbage: 'cabbage raw',
  'red cabbage': 'red cabbage raw',
  'napa cabbage': 'napa cabbage raw',
  'bok choy': 'bok choy raw',
  eggplant: 'eggplant raw',
  aubergine: 'eggplant raw',
  carrots: 'carrots raw',
  carrot: 'carrots raw',
  corn: 'corn sweet raw',
  'sweet corn': 'corn sweet raw',
  peas: 'peas green raw',
  'green peas': 'peas green raw',
  'snap peas': 'snap peas raw',
  'sugar snap peas': 'snap peas raw',
  'snow peas': 'snow peas raw',
  edamame: 'edamame shelled cooked',
  artichoke: 'artichoke raw',
  'artichoke hearts': 'artichoke hearts canned',
  beets: 'beet raw',
  beet: 'beet raw',
  beetroot: 'beet raw',
  radish: 'radish raw',
  radishes: 'radish raw',
  turnip: 'turnip raw',
  parsnip: 'parsnip raw',
  'brussels sprouts': 'brussels sprouts raw',
  'brussel sprouts': 'brussels sprouts raw',
  okra: 'okra raw',
  'collard greens': 'collard greens raw',
  'swiss chard': 'swiss chard raw',
  chard: 'swiss chard raw',
  watercress: 'watercress raw',
  fennel: 'fennel bulb raw',
  'bean sprouts': 'bean sprouts mung raw',
  sprouts: 'bean sprouts mung raw',
  'water chestnuts': 'water chestnuts canned',
  'bamboo shoots': 'bamboo shoots canned',
  jicama: 'jicama raw',
  daikon: 'daikon radish raw',
  'daikon radish': 'daikon radish raw',
  plantain: 'plantain raw',
  plantains: 'plantain raw',
  'frozen peas': 'peas green frozen',
  'frozen corn': 'corn frozen',
  'frozen broccoli': 'broccoli frozen',
  'frozen spinach': 'spinach frozen',
  'frozen mixed vegetables': 'mixed vegetables frozen',

  // ======== FRUITS ========
  banana: 'banana raw',
  apple: 'apple raw with skin',
  berries: 'mixed berries raw',
  'mixed berries': 'mixed berries raw',
  blueberries: 'blueberries raw',
  strawberries: 'strawberries raw',
  raspberries: 'raspberries raw',
  blackberries: 'blackberries raw',
  cranberries: 'cranberries raw',
  'dried cranberries': 'cranberries dried sweetened',
  avocado: 'avocado raw',
  mango: 'mango raw',
  pineapple: 'pineapple raw',
  peach: 'peach raw',
  peaches: 'peach raw',
  pear: 'pear raw',
  grapes: 'grapes raw',
  watermelon: 'watermelon raw',
  cantaloupe: 'cantaloupe raw',
  orange: 'orange raw',
  oranges: 'orange raw',
  grapefruit: 'grapefruit raw',
  lemon: 'lemon raw',
  lime: 'lime raw',
  'lemon juice': 'lemon juice fresh',
  'lime juice': 'lime juice fresh',
  'lemon zest': 'lemon peel raw',
  'orange juice': 'orange juice fresh',
  kiwi: 'kiwi raw',
  papaya: 'papaya raw',
  pomegranate: 'pomegranate raw',
  'pomegranate seeds': 'pomegranate seeds raw',
  fig: 'fig raw',
  figs: 'fig raw',
  'dried figs': 'figs dried',
  dates: 'dates medjool',
  'medjool dates': 'dates medjool',
  raisins: 'raisins',
  'dried apricots': 'apricots dried',
  prunes: 'prunes dried',
  coconut: 'coconut meat raw',
  'shredded coconut': 'coconut shredded dried',
  'coconut flakes': 'coconut flakes dried',
  cherries: 'cherries sweet raw',
  'frozen berries': 'mixed berries frozen',
  'frozen strawberries': 'strawberries frozen',
  'frozen blueberries': 'blueberries frozen',
  'frozen mango': 'mango frozen',
  applesauce: 'applesauce unsweetened',

  // ======== DAIRY & FATS ========
  'greek yogurt': 'greek yogurt plain nonfat',
  'plain greek yogurt': 'greek yogurt plain nonfat',
  'full fat greek yogurt': 'greek yogurt plain whole milk',
  yogurt: 'yogurt plain low fat',
  'plain yogurt': 'yogurt plain low fat',
  cheese: 'cheddar cheese',
  'cheddar cheese': 'cheddar cheese',
  'swiss cheese': 'swiss cheese',
  'gouda cheese': 'gouda cheese',
  'goat cheese': 'goat cheese soft',
  butter: 'butter salted',
  'unsalted butter': 'butter unsalted',
  ghee: 'ghee clarified butter',
  'clarified butter': 'ghee clarified butter',
  'olive oil': 'olive oil',
  'extra virgin olive oil': 'olive oil extra virgin',
  'coconut oil': 'coconut oil',
  'sesame oil': 'sesame oil',
  'avocado oil': 'avocado oil',
  'vegetable oil': 'vegetable oil',
  'canola oil': 'canola oil',
  milk: 'milk whole',
  'whole milk': 'milk whole',
  'skim milk': 'milk nonfat skim',
  '2% milk': 'milk reduced fat 2%',
  'oat milk': 'oat milk',
  'almond milk': 'almond milk unsweetened',
  'coconut milk': 'coconut milk canned',
  'coconut cream': 'coconut cream',
  'soy milk': 'soy milk unsweetened',
  'heavy cream': 'heavy whipping cream',
  'heavy whipping cream': 'heavy whipping cream',
  'sour cream': 'sour cream',
  'half and half': 'half and half',
  'cottage cheese': 'cottage cheese low fat 2%',
  'cream cheese': 'cream cheese',
  parmesan: 'parmesan cheese grated',
  'parmesan cheese': 'parmesan cheese grated',
  'grated parmesan': 'parmesan cheese grated',
  mozzarella: 'mozzarella cheese',
  'mozzarella cheese': 'mozzarella cheese',
  'fresh mozzarella': 'mozzarella cheese fresh',
  feta: 'feta cheese crumbled',
  'feta cheese': 'feta cheese crumbled',
  ricotta: 'ricotta cheese part skim',
  'ricotta cheese': 'ricotta cheese part skim',
  mascarpone: 'mascarpone cheese',
  paneer: 'paneer cheese',
  halloumi: 'halloumi cheese',

  // ======== NUTS & SEEDS ========
  almonds: 'almonds raw',
  'sliced almonds': 'almonds sliced',
  walnuts: 'walnuts raw',
  'peanut butter': 'peanut butter smooth',
  'natural peanut butter': 'peanut butter smooth',
  'crunchy peanut butter': 'peanut butter crunchy',
  'almond butter': 'almond butter',
  'cashew butter': 'cashew butter',
  peanuts: 'peanuts raw',
  'chia seeds': 'chia seeds dried',
  'flax seeds': 'flax seeds ground',
  flaxseed: 'flax seeds ground',
  'ground flaxseed': 'flax seeds ground',
  'flaxseed meal': 'flax seeds ground',
  'hemp seeds': 'hemp seeds hulled',
  'hemp hearts': 'hemp seeds hulled',
  'pumpkin seeds': 'pumpkin seeds raw',
  pepitas: 'pumpkin seeds raw',
  'sunflower seeds': 'sunflower seed kernels',
  cashews: 'cashews raw',
  pecans: 'pecans raw',
  'pine nuts': 'pine nuts dried',
  pistachios: 'pistachios raw',
  'macadamia nuts': 'macadamia nuts raw',
  'brazil nuts': 'brazil nuts raw',
  hazelnuts: 'hazelnuts raw',
  'mixed nuts': 'mixed nuts raw',
  'coconut butter': 'coconut butter',

  // ======== LEGUMES ========
  'black beans': 'black beans cooked',
  'canned black beans': 'black beans canned drained',
  chickpeas: 'chickpeas cooked',
  'garbanzo beans': 'chickpeas cooked',
  'canned chickpeas': 'chickpeas canned drained',
  lentils: 'lentils cooked',
  'red lentils': 'lentils red cooked',
  'green lentils': 'lentils green cooked',
  'brown lentils': 'lentils cooked',
  'kidney beans': 'kidney beans cooked',
  'white beans': 'white beans cooked',
  'cannellini beans': 'white beans cooked',
  'navy beans': 'navy beans cooked',
  'great northern beans': 'great northern beans cooked',
  'pinto beans': 'pinto beans cooked',
  'lima beans': 'lima beans cooked',
  'refried beans': 'refried beans',
  'split peas': 'split peas cooked',
  'black eyed peas': 'black eyed peas cooked',
  'black-eyed peas': 'black eyed peas cooked',
  hummus: 'hummus',
  'fava beans': 'fava beans cooked',

  // ======== CONDIMENTS & SAUCES ========
  'soy sauce': 'soy sauce',
  'low sodium soy sauce': 'soy sauce low sodium',
  tamari: 'tamari soy sauce',
  'coconut aminos': 'coconut aminos',
  'fish sauce': 'fish sauce',
  sriracha: 'sriracha hot chili sauce',
  'hot sauce': 'hot sauce',
  mirin: 'rice wine mirin',
  tahini: 'tahini sesame paste',
  'sesame paste': 'tahini sesame paste',
  mustard: 'mustard prepared yellow',
  'dijon mustard': 'mustard dijon',
  'whole grain mustard': 'mustard whole grain',
  ketchup: 'ketchup',
  mayonnaise: 'mayonnaise',
  mayo: 'mayonnaise',
  'balsamic vinegar': 'balsamic vinegar',
  'apple cider vinegar': 'apple cider vinegar',
  'red wine vinegar': 'red wine vinegar',
  'rice vinegar': 'rice vinegar',
  vinegar: 'white vinegar',
  'worcestershire sauce': 'worcestershire sauce',
  'hoisin sauce': 'hoisin sauce',
  'oyster sauce': 'oyster sauce',
  'teriyaki sauce': 'teriyaki sauce',
  'bbq sauce': 'barbecue sauce',
  'barbecue sauce': 'barbecue sauce',
  'marinara sauce': 'marinara sauce',
  pesto: 'pesto basil',
  'basil pesto': 'pesto basil',
  salsa: 'salsa',
  guacamole: 'guacamole',
  harissa: 'harissa paste',
  'harissa paste': 'harissa paste',
  'sambal oelek': 'sambal oelek chili paste',
  'chili paste': 'chili paste',
  'red curry paste': 'red curry paste',
  'green curry paste': 'green curry paste',
  'curry paste': 'red curry paste',
  'miso paste': 'miso paste',
  miso: 'miso paste',
  'white miso': 'miso paste white',
  'nutritional yeast': 'nutritional yeast',

  // ======== EXOTIC / KNOWN FAILURES ========
  galangal: 'ginger root raw',
  gochujang: 'gochujang korean chili paste',
  'gochujang paste': 'gochujang korean chili paste',
  nori: 'seaweed nori dried',
  'nori sheets': 'seaweed nori dried',
  seaweed: 'seaweed nori dried',
  wakame: 'seaweed wakame dried',
  kombu: 'seaweed kombu dried',
  lemongrass: 'lemongrass raw',
  'kaffir lime leaves': 'lime leaves',
  'thai basil': 'basil fresh',
  'star anise': 'star anise',
  tamarind: 'tamarind paste',
  'tamarind paste': 'tamarind paste',
  'palm sugar': 'palm sugar',
  jaggery: 'palm sugar',
  panko: 'panko breadcrumbs',
  furikake: 'furikake rice seasoning',
  'bonito flakes': 'bonito flakes dried',
  dashi: 'dashi stock',
  'shaoxing wine': 'shaoxing rice wine',
  'rice wine': 'rice wine mirin',
  kimchi: 'kimchi',
  sauerkraut: 'sauerkraut',
  'pickled ginger': 'ginger pickled',

  // ======== SWEETENERS & BAKING ========
  sugar: 'sugar granulated',
  'brown sugar': 'brown sugar packed',
  'powdered sugar': 'sugar powdered',
  honey: 'honey',
  'maple syrup': 'maple syrup',
  'agave nectar': 'agave nectar',
  agave: 'agave nectar',
  molasses: 'molasses',
  'coconut sugar': 'coconut sugar',
  'baking powder': 'baking powder',
  'baking soda': 'baking soda',
  'vanilla extract': 'vanilla extract',
  vanilla: 'vanilla extract',
  'cocoa powder': 'cocoa powder unsweetened',
  'cacao powder': 'cacao powder raw',
  'dark chocolate': 'dark chocolate 70%',
  'chocolate chips': 'chocolate chips semisweet',
  'cacao nibs': 'cacao nibs',

  // ======== HERBS & SPICES ========
  basil: 'basil fresh',
  'fresh basil': 'basil fresh',
  'dried basil': 'basil dried',
  cilantro: 'cilantro raw',
  'fresh cilantro': 'cilantro raw',
  parsley: 'parsley fresh',
  'fresh parsley': 'parsley fresh',
  mint: 'mint fresh',
  'fresh mint': 'mint fresh',
  dill: 'dill fresh',
  'fresh dill': 'dill fresh',
  rosemary: 'rosemary fresh',
  'fresh rosemary': 'rosemary fresh',
  thyme: 'thyme fresh',
  'fresh thyme': 'thyme fresh',
  oregano: 'oregano dried',
  'dried oregano': 'oregano dried',
  sage: 'sage fresh',
  chives: 'chives raw',
  tarragon: 'tarragon fresh',
  'bay leaf': 'bay leaf dried',
  'bay leaves': 'bay leaf dried',
  cumin: 'cumin ground',
  'ground cumin': 'cumin ground',
  'cumin seeds': 'cumin seed',
  coriander: 'coriander ground',
  'ground coriander': 'coriander ground',
  turmeric: 'turmeric ground',
  'ground turmeric': 'turmeric ground',
  'fresh turmeric': 'turmeric root raw',
  paprika: 'paprika',
  'smoked paprika': 'paprika smoked',
  'cayenne pepper': 'cayenne pepper',
  cayenne: 'cayenne pepper',
  'chili powder': 'chili powder',
  'red pepper flakes': 'red pepper flakes crushed',
  'crushed red pepper': 'red pepper flakes crushed',
  'black pepper': 'black pepper ground',
  pepper: 'black pepper ground',
  salt: 'salt table',
  'sea salt': 'salt sea',
  'kosher salt': 'salt kosher',
  cinnamon: 'cinnamon ground',
  'ground cinnamon': 'cinnamon ground',
  nutmeg: 'nutmeg ground',
  cloves: 'cloves ground',
  allspice: 'allspice ground',
  cardamom: 'cardamom ground',
  'ground cardamom': 'cardamom ground',
  'garam masala': 'garam masala',
  'curry powder': 'curry powder',
  'italian seasoning': 'italian seasoning',
  'onion powder': 'onion powder',
  'garlic powder': 'garlic powder',

  // ======== MISCELLANEOUS ========
  olives: 'olives black canned',
  'black olives': 'olives black canned',
  'green olives': 'olives green',
  'kalamata olives': 'olives kalamata',
  capers: 'capers canned',
  'roasted red peppers': 'roasted red peppers jarred',
  'coconut water': 'coconut water',
  'light coconut milk': 'coconut milk light canned',
  broth: 'chicken broth',
  'chicken broth': 'chicken broth',
  'chicken stock': 'chicken stock',
  'beef broth': 'beef broth',
  'vegetable broth': 'vegetable broth',
  'bone broth': 'bone broth chicken',
  'sesame seeds': 'sesame seeds',
  'toasted sesame seeds': 'sesame seeds toasted',
  'flax meal': 'flax seeds ground',
  'goji berries': 'goji berries dried',
};

async function main() {
  const prisma = new PrismaClient();

  try {
    console.warn(`Seeding ${Object.keys(INGREDIENT_NAME_MAP).length} food aliases...`);

    let resolved = 0;
    let resolvedWithNutrition = 0;
    let unresolved = 0;

    for (const [alias, canonicalName] of Object.entries(INGREDIENT_NAME_MAP)) {
      // Try to resolve fdcId via tsvector search
      const rows = (await prisma.$queryRawUnsafe(
        `SELECT "fdcId" FROM "UsdaFood"
         WHERE "searchVector" @@ plainto_tsquery('english', $1)
         ORDER BY ts_rank("searchVector", plainto_tsquery('english', $1)) DESC
         LIMIT 1`,
        canonicalName
      )) as { fdcId: number }[];

      const fdcId = rows.length > 0 ? rows[0].fdcId : null;

      // Extract per100g nutrition from UsdaFood nutrients JSON if we have an fdcId
      let per100gKcal: number | null = null;
      let per100gProtein: number | null = null;
      let per100gCarbs: number | null = null;
      let per100gFat: number | null = null;

      if (fdcId) {
        try {
          const usdaFood = await prisma.usdaFood.findUnique({
            where: { fdcId },
            select: { nutrients: true },
          });
          if (usdaFood?.nutrients && typeof usdaFood.nutrients === 'object') {
            const nutrients = usdaFood.nutrients as Record<string, number>;
            // Nutrient numbers: 203=protein, 204=fat, 205=carbs, 208=energy(kcal)
            per100gKcal = nutrients['208'] ?? null;
            per100gProtein = nutrients['203'] ?? null;
            per100gCarbs = nutrients['205'] ?? null;
            per100gFat = nutrients['204'] ?? null;
          }
        } catch {
          // Failed to extract nutrition — leave per100g fields null
        }
      }

      await prisma.foodAlias.upsert({
        where: { alias },
        create: {
          alias,
          canonicalName,
          usdaFdcId: fdcId,
          priority: 0,
          per100gKcal,
          per100gProtein,
          per100gCarbs,
          per100gFat,
        },
        update: {
          canonicalName,
          usdaFdcId: fdcId,
          per100gKcal,
          per100gProtein,
          per100gCarbs,
          per100gFat,
        },
      });

      if (fdcId) {
        resolved++;
        if (per100gKcal !== null) {
          resolvedWithNutrition++;
        }
      } else {
        unresolved++;
        console.warn(`  [MISS] "${alias}" → "${canonicalName}" (no fdcId found)`);
      }
    }

    console.warn(
      `\nDone! ${resolved} resolved with fdcId (${resolvedWithNutrition} with per100g nutrition), ${unresolved} without.`
    );
  } finally {
    await prisma.$disconnect();
  }
}

main().catch((err) => {
  console.error('Seed failed:', err);
  process.exit(1);
});
